name: Maintenance Event
description: Schedule a work window for maintenance
title: "[Scheduled Maintenance] Site down for Maintenance"
labels: 
  - maintenance
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## Maintenance Schedule

  - type: input
    id: start
    attributes:
      label: "Start Time"
      description: "When the maintenance window will start"
      value: "2021-08-24T13:00:00.220Z"

  - type: input
    id: end
    attributes:
      label: "End Time"
      description: "When the maintenance window will end"
      value: "2021-08-24T14:00:00.220Z"

  - type: dropdown
    id: expectedDown
    attributes:
      label: "Expected Services Affected"
      description: "Select the services expected to be affected"
      multiple: true
      options:
        - google
        - hacker-news

  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Provide further information on why this maintenance is happening"
